name: merge
on:
  push:
    branches:
      - master
      - develop
      - alpha
      - beta

env:
  NODE_VERSION: "14"
  JAVA_VERSION: "11"
  BASE_DIR: "app"

jobs:
  filter:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2

  test:
    runs-on: ubuntu-latest
    needs: filter
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ env.JAVA_VERSION }}
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: unit-test
      run: |
        mvn clean test -U
      working-directory: ${{ env.BASE_DIR }}/bulkloader
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

  build:
    runs-on: ubuntu-latest
    needs: filter
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install dependencies
        run: |
          npm install -g bower
          npm install -g grunt-cli
        working-directory: ${{ env.BASE_DIR }}/bulkloader
      - name: Build job
        run: |
          mvn -s ./settings.xml clean grunt:create-resources grunt:npm grunt:bower grunt:grunt -P elements-local
        working-directory: ${{ env.BASE_DIR }}/bulkloader 
      - name: upload build folder
        uses: actions/upload-artifact@v2
        with:
          name: webapp
          path: ${{ env.BASE_DIR }}/bulkloader/target-grunt/webapp